import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import home_style from "@/styles/Home.module.css";
import Sidebar from "@/components/sidebar";
import ClientList from "@/components/clientList";
import ClientAdd from "@/components/clientAdd";
import { useState } from "react";
import ClientView from "@/components/clientView";
import ProductList from "@/components/productList";
import ProductAdd from "@/components/productAdd";
import OrderList from "@/components/orderList";
import OrderAdd from "@/components/orderAdd";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [listClientIsOpen, setListClientIsOpen] = useState(false);
  const [addClientIsOpen, setAddClientIsOpen] = useState(false);
  const [editClientIsOpen, setEditClientIsOpen] = useState(false);
  const [client, setClient] = useState({});
  const [clientViewIsOpen, setClientViewIsOpen] = useState(false);
  const [productListIsOpen, setProductListIsOpen] = useState(false);
  const [productAddIsOpen, setProductAddIsOpen] = useState(false);
  const [orderListIsOpen, setOrderListIsOpen] = useState(false);
  const [orderAddIsOpen, setOrderAddIsOpen] = useState(false);

  const handleAddClick = () => {
    setAddClientIsOpen(true);
  };

  const handleAddClose = () => {
    setAddClientIsOpen(false);
  };

  const handleListClick = () => {
    setListClientIsOpen(true);
  };

  const handleListClose = () => {
    setListClientIsOpen(false);
  };

  const handleEditClick = () => {
    setEditClientIsOpen(true);
  };

  const handleEditClose = () => {
    setEditClientIsOpen(false);
  };

  const handleViewClick = () => {
    setClientViewIsOpen(true);
  };

  const handleViewClose = () => {
    setClientViewIsOpen(false);
  };

  const handleProductListClick = () => {
    setProductListIsOpen(true);
  };

  const handleProductListClose = () => {
    setProductListIsOpen(false);
  };

  const handleProductAddClick = () => {
    setProductAddIsOpen(true);
  };

  const handleProductAddClose = () => {
    setProductAddIsOpen(false);
  };

  const handleOrderListClick = () => {
    setOrderListIsOpen(true);
  };

  const handleOrderListClose = () => {
    setOrderListIsOpen(false);
  };

  const handleOrderAddClick = () => {
    setOrderAddIsOpen(true);
  };

  const handleOrderAddClose = () => {
    setOrderAddIsOpen(false);
  };
  return (
    <>
      <Head>
        <title>HSTAR, le CRM qu'on M</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Sidebar
        openList={handleListClick}
        closeList={handleListClose}
        openAdd={handleAddClick}
        closeAdd={handleAddClose}
        closeEdit={handleEditClose}
        closeView={handleViewClose}
        openProductList={handleProductListClick}
        closeProductList={handleProductListClose}
        openProductAdd={handleProductAddClick}
        closeProductAdd={handleProductAddClose}
        openOrderList={handleOrderListClick}
        closeOrderList={handleOrderListClose}
        openOrderAdd={handleOrderAddClick}
        closeOrderAdd={handleOrderAddClose}
      />
      {listClientIsOpen && (
        <ClientList
          openEdit={handleEditClick}
          getClient={setClient}
          closeList={handleListClose}
          openClientView={handleViewClick}
          closeView={handleViewClose}
        />
      )}
      {addClientIsOpen && (
        <ClientAdd closeEdit={handleEditClose} openList={handleListClick} />
      )}
      {editClientIsOpen && (
        <ClientAdd
          useClient={client}
          closeEdit={handleEditClose}
          openList={handleListClick}
        />
      )}
      {clientViewIsOpen && (
        <ClientView useClient={client} closeView={handleViewClose} />
      )}
      {productListIsOpen && <ProductList />}
      {productAddIsOpen && <ProductAdd />}
      {orderListIsOpen && <OrderList />}
      {orderAddIsOpen && <OrderAdd />}
      {!listClientIsOpen &&
        !addClientIsOpen &&
        !editClientIsOpen &&
        !clientViewIsOpen &&
        !productListIsOpen &&
        !productAddIsOpen &&
        !orderListIsOpen &&
        !orderAddIsOpen && (
          <div>
            <h2>Bienvenue sur HSTAR, le CRM qu'on M</h2>

            <div>
              <Image
                src="/vignetteClientList.png"
                alt="Picture of the author"
                unoptimized={true}
                height={250}
                width={400}
                className={home_style.vignette}
              />
            </div>
          </div>
        )}
    </>
  );
}
