import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import Array from '@/components/array'


const inter = Inter({ subsets: ['latin'] })
const tableau = [['Monsieur', 'Bidule',3000],['Madame', 'machine', 5000], ['Bernard','Arnault',500000, "Grand compte"]]
const thead = ['Nom', 'Prénom', 'Chiffre d\'affaire', 'Nature']
export default function Home() {
  return (
    <>
      <Head>
        <title>HSTAR, le CRM qu'on M</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
      
      </main>
    </>
  )
}
